---
abstract: 'Do Nagios commands remotely.'
author:
  - 'Brian Smith <brian@palominodb.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-RemoteCmd
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::SSLeay: 0
  DateTime: 0
  LWP: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
